-- MySQL Workbench Synchronization
-- Generated: 2015-07-08 10:26
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Bernd Schmidt

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `ajdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `ajdb`.`TITEL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `BEZEICHNUNG` VARCHAR(100) NOT NULL COMMENT 'Titelbezeichnung',
  `PERSON_ID` INT(11) NOT NULL COMMENT '',
  `ERSCHDATUM` DATE NULL DEFAULT NULL COMMENT '',
  `LIVE` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `FK_TITEL_PERSON_ID_idx` (`PERSON_ID` ASC)  COMMENT '',
  CONSTRAINT `FK_TITEL_PERSON_ID`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `ajdb`.`PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Hauptabelle vorerst für Songtitel';

CREATE TABLE IF NOT EXISTS `ajdb`.`MUSIKDIGITAL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `DATENTRAEGER` VARCHAR(100) NOT NULL COMMENT '',
  `PFAD` VARCHAR(100) NOT NULL COMMENT '',
  `FORMAT` VARCHAR(100) NOT NULL COMMENT 'Dateiformat',
  `QUALITAET` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ajdb`.`PERSON` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NAME` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `NAME_1` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `KNAME` VARCHAR(40) NOT NULL COMMENT 'Künstlername',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ajdb`.`TITEL_MUSIKDIGITAL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TITEL_ID` INT(11) NOT NULL COMMENT '',
  `MUSIKDIGTAL_ID` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_TITEL_MUSIKDIGITAL_1_idx` (`TITEL_ID` ASC)  COMMENT '',
  INDEX `fk_TITEL_MUSIKDIGITAL_2_idx` (`MUSIKDIGTAL_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_TITEL_MUSIKDIGITAL_1`
    FOREIGN KEY (`TITEL_ID`)
    REFERENCES `ajdb`.`TITEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TITEL_MUSIKDIGITAL_2`
    FOREIGN KEY (`MUSIKDIGTAL_ID`)
    REFERENCES `ajdb`.`MUSIKDIGITAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
